/** @format */

// import LocalizedStrings from 'react-native-localization'

/* API
 setLanguage(languageCode) - to force manually a particular language
 getLanguage() - to get the current displayed language
 getInterfacebookLanguage() - to get the current device interface language
 formatString() - to format the passed string replacing its placeholders with the other arguments strings
 */
import   Localization from '@custom/Localization';

const langs = {
  en: {
    //Root (Home)
    home: 'Home',
    readlater: 'Read Later',
    category: 'Category',
    categories: 'Categories',
    back: ' Back',
    textFilter: 'Recent',
    browseNearBy: 'Browse More Places',
    seeAll: ' See All',
    youMayLike: 'You might like',
    foodAndDrink: 'Food & Drink experiences',
    grabFood: 'Grab Food To Go',
    readMore: 'See More',
    reload: 'Reload',
    skip: 'Get Started',

    //Login Form
    passwordUp: 'PASSWORD',
    passwordnor: 'password',
    forgotPassword: 'Forget password',
    for: 'Forgot Password',
    login: 'Login',
    loginSuccess: 'Sign In Successfull',
    noAccount: 'Do not have an account?',
    signup: 'Sign Up',
    signupSuccess: 'Sign Up Successfull',
    facebook: 'Facebook',

    // MenuSide
    news: 'News',
    listing: 'Discover',
    contact: 'Contact',
    aboutus: 'About',
    setting: 'Setting',
    search: 'Search',
    logout: 'Logout',
    explore: 'Explore',

    //panel
    loading: 'LOADING...',

    // Post
    post: 'Post',
    posts: 'Posts',
    feature: 'Feature articles',
    days: 'days',
    editorchoice: 'Editor Choice',

    // PostDetail
    comment: 'Leave a review',
    yourcomment: 'Your comment',
    placeComment:
      'Tell something about your experience or leave a tip for others',
    writeReview: 'Write A Review',
    thanksForReview:
      'Thanks for the review, your content will be verify by the admin and will be published later',
    errInputComment: 'Please input your content to submit',
    errRatingComment: 'Please rating to submit',
    relatedPost: 'Related Post',

    all: 'All',
    forLife: 'for lifestyle people',
    powerBy: 'Power by Carnival',
    video: 'Video',
    fontSize: 'Content font size',
    email: 'EMAIL',
    enterEmail: 'Enter your email',
    enterPassword: 'Type your password',
    photo: 'Photo',
    clear: 'Clear All',
    by: 'by',
    name: 'NAME',
    enterName: 'Enter name',
    send: 'Send',
    commentSubmit: 'Your Comment is sent and waiting for approving',
    recent: 'Recent Posts',
    hoursWorking: 'Hours Working',
    reviews: 'Reviews',
    descriptionMap: 'Description',
    seeAllMore: 'See All',
    reserve: 'Booking',
    viewMapFull: 'Get Directions',
    booking: 'Booking',
    location: 'Location',
    open: 'Open',
    tel: 'Tel',
    twitter: 'Twitter',
    website: 'Website',
    photoGalleryTitle: 'Photo Gallery',
    descriptionList: 'Description',
    noResult: 'No result',
    chatWithUs: 'Chat with us...',
    share: 'Share',

    //Layout
    cardView: 'Card ',
    simpleView: 'List View',
    twoColumnView: 'Two Column ',
    threeColumnView: 'Three Column ',
    listView: 'List View',
    default: 'Default',
    advanceView: 'Advance ',

    //readlater
    textBookMark: 'Bookmarks',
    textPosts: 'Posts',
    noBookmark: 'There is no bookmark item',
    ago: 'ago',
    allCategory: 'All Category',

    //Booking,
    noChosenDate: 'Please choose Date for Your Booking',
    selectPersonHeading: 'Number of seat:',
    startDate: 'START',
    endDate: 'END',
    ThankYou: 'Thank you',
    FinishOrder:
      "Thank you so much for your purchased, we'll contact you as soon as possible",
    myBookings: 'My Bookings',
    viewMyBookings: 'View Your Bookings',
    notMinToZero: 'Number of person not less zero',
    notNumPersonThanThree: 'Number of Person not than three number',
    emptyDate: 'Your booking is empty!',
    textStart: 'Start Time',
    textEnd: 'End time',
    timeStart: 'Start Time',
    timeEnd: 'End time',
    noTimeStart: 'Select Start Time',
    noTimeEnd: 'Select End Time',

    //Orders
    BookingDate: 'Date Booking',
    BookingFeatureImage: 'Feature Image',
    BookingPlace: 'Place',
    BookingNumOfPersons: 'Seat(s)',
    BookingDateStart: 'Start',
    BookingDateEnd: 'End',

    noConnection: 'NO INTERNET ACCESS',
    canNotGetData: "Can't get data from server",
    selectOnCalendar: 'Select booking date:',
    placeToVisit: 'places to visit',

    // Posts:
    emptyPosts: 'There is no posts on your account',

    // user profile
    userProfileName: 'Name',
    userProfileEmail: 'Email',
    userProfileAddress: 'Address',
    userProfileWishlist: 'Wishlist',
    userProfileLanguages: 'Languages',
    userProfilePushNotif: 'Push notification',
    userProfilePrivacy: 'Privacy',
    userProfileContact: 'Contact us',
    userProfileAbout: 'About us',
    userProfileItems: 'items',
    chatList: 'Chat List',

    // search screen
    recents: 'Recents',
    filter: 'Filters by: ',

    //language
    currentLanguage: 'Current Language',
    SwitchRtlConfirm: 'Switch language require an app reload, continue?',
    Confirm: 'Confirm',
    changeLanguage: 'Change Language',
    OK: 'OK',
    CANCEL: 'CANCEL',
    next: 'next',

    //chat
    typeAmessage: 'Type a message here',

    // Cart screen
    Back: 'Back',
    Loading: 'Loading',
    NextStep: 'Next Step',
    // Cart
    NoCartItem: 'There is no product in cart',
    Total: 'Total',
    EmptyCheckout: "Sorry, you can't check out an empty cart",
    RemoveCartItemConfirm: 'Remove this product from cart?',
    MyCart: 'My Cart',
    Order: 'Booking',
    ShoppingCart: 'Shopping Cart',
    ShoppingCartIsEmpty: 'Your Cart is Empty',
    Delivery: 'Customer',
    AddProductToCart: 'Add a product to the shopping cart',
    TotalPrice: 'Total Price:',
    YourDeliveryInfo: 'Your delivery info:',
    ShopNow: 'Shop Now',
    YourChoice: 'Your wishlist:',
    YourSale: 'Your Sale:',
    SubtotalPrice: 'Subtotal Price:',
    BuyNow: 'Buy Now',
    Items: 'items',
    Item: 'item',
    FinishOrderCOD: 'You can use to number of order to track shipping status',
    ConfirmOrder: 'Confirm Order',
    RequireEnterAllFileds: 'Please enter all fields',
    Error: 'Error',
    InvalidEmail: 'Invalid email address',
    Finish: 'Finish',

    // Checkout
    Checkout: 'Checkout',
    ProceedPayment: 'Proceed Payment',
    Purchase: 'Purchase',
    CashOnDelivery: 'Cash on Delivery',
    Paypal: 'Paypal',
    Stripe: 'Stripe',
    CreditCard: 'Credit Card',
    PaymentMethod: 'Payment Method - Not select',
    PaymentMethodError: 'Please select your payment method',
    PayWithCoD: 'Your purchase will be pay when goods were delivered',
    PayWithPayPal: 'Your purchase will be pay with PayPal',
    PayWithStripe:
      'Your booking deposit will be refunded after your event is complete. Please read our Booking Terms for futher details',
    ApplyCoupon: 'Apply',
    CouponPlaceholder: 'COUPON CODE',
    APPLY: 'APPLY',
    CardNamePlaceholder: 'Name written on card',
    BackToHome: 'Back to Home',
    OrderCompleted: 'Your order was completed',
    OrderCanceled: 'Your order was canceled',
    OrderFailed: 'Something went wrong...',
    OrderCompletedDesc: 'Your order id is ',
    OrderCanceledDesc:
      'You have canceled the order. The transaction has not been completed',
    OrderFailedDesc:
      'We have encountered an error while processing your order. The transaction has not been completed. Please try again',
    OrderTip:
      'Tip: You could track your order status in "My Orders" section from side menu',
    Payment: 'Payment',
    Complete: 'Complete',
    EnterYourFirstName: 'Enter your First Name',
    EnterYourLastName: 'Enter your Last Name',
    EnterYourEmail: 'Enter your email',
    EnterYourPhone: 'Enter your phone',
    EnterYourAddress: 'Enter your address',
    CreateOrderError: 'Cannot create new order. Please try again later',
    AccountNumner: 'Account number',
    CardHolderName: 'Cardholder Name',
    ExpirationDate: 'Expiration Date',
    SecurityCode: 'CVV',

    // form
    NotSelected: 'Not selected',
    EmptyError: 'This field is empty',
    DeliveryInfo: 'Delivery Info',
    FirstName: 'First Name',
    LastName: 'Last Name',
    Address: 'Address',
    State: 'State/City',
    City: 'Town/City',
    NotSelectedError: 'Please choose one',
    Postcode: 'Postcode',
    Country: 'Country',
    Email: 'Email',
    Phone: 'Phone Number',
    Note: 'Note',

    // Place holder
    TypeFirstName: 'Type your first name',
    TypeLastName: 'Type your last name',
    TypeAddress: 'Type address',
    TypeCity: 'Type your town or city',
    TypeState: 'Type your state or city',
    TypeNotSelectedError: 'Please choose one',
    TypePostcode: 'Type postcode',
    TypeEmail: 'Type email (Ex. acb@gmail.com), ',
    TypePhone: 'Type your phone number',
    TypeNote: 'Note',
    TypeCountry: 'Select country',
    SelectPayment: 'Select Payment method',
    close: 'CLOSE',

    //new listing
    publish: 'Publish',
    allowAccessCameraroll: 'You need to turn on to allow access camera roll',
    postHeading: 'Type the heading:',
    selectCategory: 'Select Category',
    errorMsgConnectServer: 'Can not connect to server.',
    submit: 'Submit',
    composeTheContent: 'Type the content...',
    readyToSubmit: 'Ready to submit?',
    notYet: 'Not yet',
    successfull: 'Successfull',
    close: 'Close',
    msgConfirmClearHistory: 'Are you sure you want to clear history?',
    confirmation: 'Confirmation',
    listingType: 'Listing Type',
    jobType: 'Job Type',
    myListings: 'My Listings',
    selectOnLocation: 'Select Location',
    location: 'Location',
    informationField: 'Fields Information',
    listingTitle: 'Type Listing Title',
    listingContent: 'Listing Content',
    listingEmpty: 'Empty Listings',

    Map: 'Map',
    List: 'List',

    // Comment
    Terrible: 'Terrible',
    Poor: 'Poor',
    Average: 'Average',
    VeryGood: 'Very Good',
    Exceptional: 'Exceptional',
    Average: 'Average',
  },
  ar: {
    //Root (Home)
    home: 'الرئيسية',
    readlater: 'القراءة لاحقاً',
    category: 'التصنيفات',
    categories: 'التصنيفات',
    back: ' العودة',
    textFilter: 'الأخيرة',
    browseNearBy: 'تصفح المزيد من الأماكن',
    seeAll: ' See All',
    youMayLike: 'You might like',
    foodAndDrink: 'Food & Drink experiences',
    grabFood: 'Grab Food To Go',
    readMore: 'See More',
    reload: 'Reload',
    skip: 'Get Started',

    //Login Form
    passwordUp: 'كلمة المرور',
    passwordnor: 'كلمة المرور',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    login: 'تسجيل الدخول',
    loginSuccess: '',
    noAccount: 'لا تملك حساب؟',
    signup: 'تسجيل جديد',
    singupSuccess: '',
    facebook: 'فيس بوك',

    // MenuSide
    news: 'الأخبار',
    listing: 'الأخبار',
    contact: 'إتصل بنا',
    aboutus: 'من نحن؟',
    setting: 'اعدادات',
    search: 'بحث',
    logout: 'تسجيل خروج ',
    explore: 'يكتشف',

    //panel
    loading: 'LOADING...',

    // Post
    post: 'خبر',
    posts: 'أخبار',
    feature: 'أخبار مميزة',
    days: 'أيام',
    editorchoice: 'مختارة لكم',

    // PostDetail
    comment: 'تعليق',
    yourcomment: 'تعليقك',
    relatedPost: 'أخبار مقترحة',

    all: 'الكل',
    forLife: 'للمهتمين في ستايل الحياة',
    powerBy: 'تدار من قبل',
    video: 'فيديو',
    fontSize: 'حجم الخط',
    email: 'البريد الالكتروني',
    enterEmail: 'أدخل البريد الالكتروني',
    enterPassword: 'أدخل الرقم السري ',
    photo: 'صورة',
    clear: 'مسح',
    by: 'من قبل',
    name: 'الاسم',
    enterName: 'ادخل الاسم',
    send: 'ارسال',
    commentSubmit: 'تم ارسال تعليقك، بإنتظار الموافقة عليه',
    recent: 'الحديثة',
    hoursWorking: 'ساعات اليوم',
    reviews: 'استعراض',
    descriptionMap: 'وصف',
    seeAllMore: 'اظهار الكل',
    reserve: 'الاحتياطي',
    viewMapFull: 'إعرض الخريطة',
    booking: 'الحجز',
    location: 'موقعك',
    open: 'Open',
    tel: 'Tel',
    twitter: 'Twitter',
    website: 'Website',
    photoGalleryTitle: 'معرض الصور',
    descriptionList: 'وصف',
    chatWithUs: 'Chat with us...',

    //Layout
    cardView: 'عرض البطاقة',
    simpleView: 'عرض بسيط',
    twoColumnView: 'اثنين من عرض العمود',
    listView: 'عرض القائمة',
    advanceView: 'عرض مقدما',

    //readlater
    textBookMark: 'إرسال',
    textPosts: 'المشاركات',
    noBookmark: 'لا يوجد عنصر إشارة مرجعية',
    ago: 'ago',
    allCategory: 'كل فئة',

    //Booking,
    noChosenDate: 'يرجى اختيار تاريخ الحجز',
    selectPersonHeading: 'يرجى اختيار عدد الأشخاص لحجزك',
    startDate: 'Start',
    endDate: 'End',
    ThankYou: 'Thank you',
    FinishOrder:
      "Thank you so much for your purchased, we'll contact you as soon as possible",
    myBookings: 'My Bookings',
    viewMyBookings: 'View Your Bookings',
    notMinToZero: 'Number of person not less zero',
    notNumPersonThanThree: 'Number of Person not than three number',
    emptyDate: 'Your booking is empty!',
    textStart: 'Time Start',
    textEnd: 'Time End',
    timeStart: 'Pick start time ',
    timeEnd: 'Pick end time',
    noTimeStart: 'Please choose time start',
    noTimeEnd: 'Please choose time end',

    //Orders
    BookingDate: 'تاريخ الحجز',
    BookingFeatureImage: 'صورة مميزة',
    BookingPlace: 'مكان',
    BookingNumOfPersons: 'مقعد',
    BookingDateStart: 'بداية',
    BookingDateEnd: 'النهاية',

    noConnection: 'NO INTERNET ACCESS',
    canNotGetData: "Can't get data from server",
    selectOnCalendar: 'يرجى النقر على التقويم لاختيار تاريخ الحجز',
    placeToVisit: 'اماكن للزيارة',

    // Posts:
    emptyPosts: 'There is no posts on your account',

    // user profile
    userProfileName: 'اسم',
    userProfileEmail: 'البريد الإلكتروني',
    userProfileAddress: 'عنوان',
    userProfileWishlist: 'الأماني',
    userProfileLanguages: 'اللغات',
    userProfilePushNotif: 'دفع الإخطار',
    userProfilePrivacy: 'الإجمالية',
    userProfileContact: 'اتصل بنا',
    userProfileAbout: 'معلومات عنا',
    userProfileItems: 'العناصر',
    chatList: 'Chat List',

    // search screen
    recents: 'حديثي',
    filter: 'مرشحات: ',

    //language
    currentLanguage: 'اللغة الحالية',
    SwitchRtlConfirm:
      'تتطلب تبديل اللغة إعادة تحميل التطبيق ، هل تريد المتابعة؟',
    Confirm: 'تؤكد',
    changeLanguage: 'تغيير اللغة',
    OK: 'OK',
    CANCEL: 'CANCEL',
    next: 'next',

    //chat
    typeAmessage: 'Type a message here',

    // Cart screen
    Back: 'Back',
    Loading: 'Loading',
    NextStep: 'Next Step',
    // Cart
    NoCartItem: 'There is no product in cart',
    Total: 'Total',
    EmptyCheckout: "Sorry, you can't check out an empty cart",
    RemoveCartItemConfirm: 'Remove this product from cart?',
    MyCart: 'Booking',
    Order: 'Booking',
    ShoppingCart: 'Shopping Cart',
    ShoppingCartIsEmpty: 'Your Cart is Empty',
    Delivery: 'Customer',
    AddProductToCart: 'Add a product to the shopping cart',
    TotalPrice: 'Total Price:',
    YourDeliveryInfo: 'Your delivery info:',
    ShopNow: 'Shop Now',
    YourChoice: 'Your wishlist:',
    YourSale: 'Your Sale:',
    SubtotalPrice: 'Subtotal Price:',
    BuyNow: 'Buy Now',
    Items: 'items',
    Item: 'item',
    FinishOrderCOD: 'You can use to number of order to track shipping status',
    ConfirmOrder: 'Confirm Order',
    RequireEnterAllFileds: 'Please enter all fields',
    Error: 'Error',
    InvalidEmail: 'Invalid email address',
    Finish: 'Finish',

    // Checkout
    Checkout: 'Checkout',
    ProceedPayment: 'Proceed Payment',
    Purchase: 'Purchase',
    CashOnDelivery: 'Cash on Delivery',
    Paypal: 'Paypal',
    Stripe: 'Stripe',
    CreditCard: 'Credit Card',
    PaymentMethod: 'Payment Method - Not select',
    PaymentMethodError: 'Please select your payment method',
    PayWithCoD: 'Your purchase will be pay when goods were delivered',
    PayWithPayPal: 'Your purchase will be pay with PayPal',
    PayWithStripe:
      'Your booking deposit will be refunded after your event is complete. Please read our Booking Terms for futher details',
    ApplyCoupon: 'Apply',
    CouponPlaceholder: 'COUPON CODE',
    APPLY: 'APPLY',
    CardNamePlaceholder: 'Name written on card',
    BackToHome: 'Back to Home',
    OrderCompleted: 'Your order was completed',
    OrderCanceled: 'Your order was canceled',
    OrderFailed: 'Something went wrong...',
    OrderCompletedDesc: 'Your order id is ',
    OrderCanceledDesc:
      'You have canceled the order. The transaction has not been completed',
    OrderFailedDesc:
      'We have encountered an error while processing your order. The transaction has not been completed. Please try again',
    OrderTip:
      'Tip: You could track your order status in "My Orders" section from side menu',
    Payment: 'Payment',
    Complete: 'Complete',
    EnterYourFirstName: 'Enter your First Name',
    EnterYourLastName: 'Enter your Last Name',
    EnterYourEmail: 'Enter your email',
    EnterYourPhone: 'Enter your phone',
    EnterYourAddress: 'Enter your address',
    CreateOrderError: 'Cannot create new order. Please try again later',
    AccountNumner: 'Account number',
    CardHolderName: 'Cardholder Name',
    ExpirationDate: 'Expiration Date',
    SecurityCode: 'CVV',

    // form
    NotSelected: 'Not selected',
    EmptyError: 'This field is empty',
    DeliveryInfo: 'Delivery Info',
    FirstName: 'First Name',
    LastName: 'Last Name',
    Address: 'Address',
    State: 'State/City',
    City: 'Town/City',
    NotSelectedError: 'Please choose one',
    Postcode: 'Postcode',
    Country: 'Country',
    Email: 'Email',
    Phone: 'Phone Number',
    Note: 'Note',

    // Place holder
    TypeFirstName: 'Type your first name',
    TypeLastName: 'Type your last name',
    TypeAddress: 'Type address',
    TypeCity: 'Type your town or city',
    TypeState: 'Type your state or city',
    TypeNotSelectedError: 'Please choose one',
    TypePostcode: 'Type postcode',
    TypeEmail: 'Type email (Ex. acb@gmail.com), ',
    TypePhone: 'Type your phone number',
    TypeNote: 'Note',
    TypeCountry: 'Select country',
    SelectPayment: 'Select Payment method',
    close: 'CLOSE',

    //new listing
    publish: 'Publish',
    allowAccessCameraroll: 'You need to turn on to allow access camera roll',
    postHeading: 'Post heading',
    selectCategory: 'Select Category',
    errorMsgConnectServer: 'Can not connect to server.',
    submit: 'Submit',
    composeTheContent: 'Type the content...',
    readyToSubmit: 'Ready to submit?',
    notYet: 'Not yet',
    successfull: 'Successfull',
    close: 'Close',
    msgConfirmClearHistory: 'Are you sure you want to clear history?',
    confirmation: 'Confirmation',
    listingType: 'Listing Type',
    jobType: 'Job Type',
    myListings: 'My Listings',
    selectOnLocation: 'Select Location',
    location: 'Location',
    informationField: 'Fields Information',
    listingTitle: 'Type Listing Title',
    listingContent: 'Listing Content',
    listingEmpty: 'Empty Listings',

    Map: 'Map',
    List: 'List',

    // Comment
    Terrible: 'Terrible',
    Poor: 'Poor',
    Average: 'Average',
    VeryGood: 'Very Good',
    Exceptional: 'Exceptional',
    Average: 'Average',
  },
  ///Put other languages here
}
const Languages = new Localization.LocaleStore(langs)
export default Languages
