/** @format */

export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS'
export const POST_FETCH_MORE = 'POST_FETCH_MORE'
export const FETCH_PENDING = 'FETCH_PENDING'

export const POST_CHANGE_LAYOUT_SUCCESS = 'POST_CHANGE_LAYOUT_SUCCESS'
export const POST_RELATED_FETCH_SUCCESS = 'POST_RELATED_FETCH_SUCCESS'

export const TAG_ON_SELECT = 'TAG_ON_SELECT'
export const TAG_FETCH_SUCCESS = 'TAG_FETCH_SUCCESS'

export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS'
export const CATEGORY_ON_SELECT = 'CATEGORY_ON_SELECT'
export const CATEGORY_SELECT_LAYOUT = 'CATEGORY_SELECT_LAYOUT'
export const CATEGORY_FETCH_PENDING = 'CATEGORY_FETCH_PENDING'
export const CATEGORY_FETCH_MORE_SUCCESS = 'CATEGORY_FETCH_MORE_SUCCESS'

export const VIDEO_FETCH_SUCCESS = 'VIDEO_FETCH_SUCCESS'
export const VIDEO_FETCH_MORE = 'VIDEO_FETCH_MORE'
export const PHOTO_FETCH_SUCCESS = 'PHOTO_FETCH_SUCCESS'
export const PHOTO_FETCH_MORE = 'PHOTO_FETCH_MORE'

export const FETCH_POST_BOOKMARK_SUCCESS = 'FETCH_POST_BOOKMARK_SUCCESS'
export const ADD_POST_BOOKMARK_SUCCESS = 'ADD_POST_BOOKMARK_SUCCESS'
export const REMOVE_POST_BOOKMARK_SUCCESS = 'REMOVE_POST_BOOKMARK_SUCCESS'

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const CLEAR_USER_SUCCESS = 'CLEAR_USER_SUCCESS'
export const FETCH_POST_BY_USER_SUCCESS = 'FETCH_POST_BY_USER_SUCCESS'
export const FETCH_POSTS_USER_MORE = 'FETCH_POSTS_USER_MORE'
export const FETCH_LISTING_BY_USER_SUCCESS = 'FETCH_LISTING_BY_USER_SUCCESS'
export const FETCH_LISTING_USER_MORE = 'FETCH_LISTING_USER_MORE'

export const FETCH_MY_ORDER = 'FETCH_MY_ORDER'
export const FETCH_ORDER_PENDING = 'FETCH_ORDER_PENDING'
export const FETCH_ORDER_ERROR = 'FETCH_ORDER_ERROR'

export const COMMENT_FETCH_SUCCESS = 'COMMENT_FETCH_SUCCESS'

export const TAG_LIST_FETCH_SUCCESS = 'TAG_LIST_FETCH_SUCCESS'
export const TAG_LIST_INIT = 'TAG_LIST_INIT'

export const POST_BY_CATES_FETCH_SUCCESS = 'POST_BY_CATES_FETCH_SUCCESS'
export const POST_BY_CATES_FETCH_MORE = 'POST_BY_CATES_FETCH_MORE'

export const POST_FETCH_MAP_MARKERS_SUCCESS = 'POST_FETCH_MAP_MARKERS_SUCCESS'

export const ADD_TOAST = 'ADD_TOAST'
export const REMOVE_TOAST = 'REMOVE_TOAST'

export const SET_REGION_MAP = 'SET_REGION_MAP'
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS'
export const SET_MY_POSITION = 'SET_MY_POSITION'

export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS'
export const FETCH_PENDING_SEARCH = 'FETCH_PENDING_SEARCH'
export const SEARCH_POSTS_STOPPED = 'SEARCH_POSTS_STOPPED'
export const SEARCH_POSTS_MAP_SUCCESS = 'SEARCH_POSTS_MAP_SUCCESS'
export const CLEAR_SEARCH_POSTS = 'CLEAR_SEARCH_POSTS'

export const UPDATE_SKIP = 'UPDATE_SKIP'

export const CLEAR_BOOKMARKS = 'CLEAR_BOOKMARKS'

export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS'

export const SEARCH_MAP_MARKER_SUCCESS = 'SEARCH_MAP_MARKER_SUCCESS'
export const SEARCH_MAP_MARKER_PENDING = 'SEARCH_MAP_MARKER_PENDING'
export const SEARCH_MAP_MARKER_STOPPED = 'SEARCH_MAP_MARKER_STOPPED'

export const POST_FETCH_NEAREST_LOCATIONS_SUCCESS =
  'POST_FETCH_NEAREST_LOCATIONS_SUCCESS'
//for mylisting
export const TAGS_FETCH_SUCCESS = 'TAGS_FETCH_SUCCESS'
export const CASE27_TYPES_FETCH_SUCCESS = 'CASE27_TYPES_FETCH_SUCCESS'
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS'
//for listify
export const REGIONS_FETCH_SUCCESS = 'REGIONS_FETCH_SUCCESS'
//for listable, jobfiy
export const JOB_TYPES_FETCH_SUCCESS = 'JOB_TYPES_FETCH_SUCCESS'

export const ITEMS_SELECTED_SEARCH = 'ITEMS_SELECTED_SEARCH'
// language
export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE'

//chat
export const SET_CHAT = 'SET_CHAT'
export const CLEAR_CHAT = 'CLEAR_CHAT'

// cart
export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const EMPTY_CART = 'EMPTY_CART'
export const CREATE_NEW_ORDER_PENDING = 'CREATE_NEW_ORDER_PENDING'
export const CREATE_NEW_ORDER_SUCCESS = 'CREATE_NEW_ORDER_SUCCESS'
export const CREATE_NEW_ORDER_ERROR = 'CREATE_NEW_ORDER_ERROR'
export const VALIDATE_CUSTOMER_INFO = 'VALIDATE_CUSTOMER_INFO'
export const INVALIDATE_CUSTOMER_INFO = 'INVALIDATE_CUSTOMER_INFO'
export const FETCH_CART_PENDING = 'FETCH_CART_PENDING'
export const GET_SHIPPING_METHOD_PENDING = 'GET_SHIPPING_METHOD_PENDING'
export const GET_SHIPPING_METHOD_SUCCESS = 'GET_SHIPPING_METHOD_SUCCESS'
export const GET_SHIPPING_METHOD_FAIL = 'GET_SHIPPING_METHOD_FAIL'
export const SELECTED_SHIPPING_METHOD = 'SELECTED_SHIPPING_METHOD'

// country
export const COUNTRY_FETCH_SUCCESS = 'COUNTRY_FETCH_SUCCESS'
export const COUNTRY_FETCHING = 'COUNTRY_FETCHING'
export const COUNTRY_FETCH_FAILURE = 'COUNTRY_FETCH_FAILURE'

// payment
export const PAYMENT_FETCH_SUCCESS = 'PAYMENT_FETCH_SUCCESS'
export const PAYMENT_FETCHING = 'PAYMENT_FETCHING'
export const PAYMENT_FETCH_FAILURE = 'PAYMENT_FETCH_FAILURE'
export const CLEAN_OLD_COUPON = 'CLEAN_OLD_COUPON'

export const CREATE_POST_PENDING = 'CREATE_POST_PENDING'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const POST_FETCH_RECENTS_SUCCESS = 'POST_FETCH_RECENTS_SUCCESS'
export const POST_FETCH_RECENTS_MORE = 'POST_FETCH_RECENTS_MORE'

export const POST_TAG_FETCH_SUCCESS = 'POST_TAG_FETCH_SUCCESS'
export const POST_TAG_FETCH_MORE = 'POST_TAG_FETCH_MORE'
